import type { Release1Store } from "@/lib/release-1/schema";

// Generated by npm run generate:release-1-data
// Excluded source titles: Farewell to Erin, Josefin's Waltz, Kitty Lie Over, Put Me in the Big Chest, The Highlander's Farewell to Ireland, The Rolling Waves, Up in the Air
export const release1FixtureStore: Release1Store = {
  "tunes": [
    {
      "id": "morrisons-jig",
      "slug": "morrisons-jig",
      "name": "Morrison's Jig",
      "tuneType": "Jig",
      "summary": "Imported from Sessions/chyunes_mbys.md."
    },
    {
      "id": "the-butterfly",
      "slug": "the-butterfly",
      "name": "The Butterfly",
      "tuneType": "Jig",
      "summary": "Imported from Sessions/chyunes_mbys.md."
    },
    {
      "id": "swallowtail-jig",
      "slug": "swallowtail-jig",
      "name": "Swallowtail Jig",
      "tuneType": "Jig",
      "summary": "Imported from Sessions/chyunes_mbys.md."
    },
    {
      "id": "saddle-the-pony",
      "slug": "saddle-the-pony",
      "name": "Saddle the Pony",
      "tuneType": "Jig",
      "summary": "Imported from Sessions/chyunes_mbys.md."
    },
    {
      "id": "lilting-banshee",
      "slug": "lilting-banshee",
      "name": "Lilting Banshee",
      "tuneType": "Jig",
      "summary": "Imported from Sessions/chyunes_mbys.md."
    },
    {
      "id": "tom-billys",
      "slug": "tom-billys",
      "name": "Tom Billy's",
      "tuneType": "Jig",
      "summary": "Imported from Sessions/chyunes_mbys.md. Ref: Saddle the Pony, Lilting Banshee/Tom Billy's (Track 1)"
    },
    {
      "id": "willie-colemans",
      "slug": "willie-colemans",
      "name": "Willie Coleman's",
      "tuneType": "Jig",
      "summary": "Imported from Sessions/chyunes_mbys.md. Chart content recovered from Sessions/2025-12_first_friday_jam.md."
    },
    {
      "id": "connaughtmans-rambles",
      "slug": "connaughtmans-rambles",
      "name": "Connaughtman's Rambles",
      "tuneType": "Jig",
      "summary": "Imported from Sessions/chyunes_mbys.md. Rolling Waves: Kevin Burke And Mícheál O’Domhnaill style"
    },
    {
      "id": "the-green-mountain",
      "slug": "the-green-mountain",
      "name": "The Green Mountain",
      "tuneType": "Reel",
      "summary": "Imported from Sessions/chyunes_mbys.md."
    },
    {
      "id": "wind-that-shakes-the-barley",
      "slug": "wind-that-shakes-the-barley",
      "name": "Wind that Shakes the Barley",
      "tuneType": "Reel",
      "summary": "Imported from Sessions/chyunes_mbys.md."
    },
    {
      "id": "swinging-on-the-gate",
      "slug": "swinging-on-the-gate",
      "name": "Swinging on the Gate",
      "tuneType": "Reel",
      "summary": "Imported from Sessions/chyunes_mbys.md."
    },
    {
      "id": "man-of-the-house",
      "slug": "man-of-the-house",
      "name": "Man of the House",
      "tuneType": "Reel",
      "summary": "Imported from Sessions/chyunes_mbys.md."
    },
    {
      "id": "jackie-colemans",
      "slug": "jackie-colemans",
      "name": "Jackie Coleman's",
      "tuneType": "Reel",
      "summary": "Imported from Sessions/chyunes_mbys.md. Ref: Track"
    },
    {
      "id": "congress-reel",
      "slug": "congress-reel",
      "name": "Congress Reel",
      "tuneType": "Reel",
      "summary": "Imported from Sessions/chyunes_mbys.md."
    },
    {
      "id": "masons-apron",
      "slug": "masons-apron",
      "name": "Mason's Apron",
      "tuneType": "Reel",
      "summary": "Imported from Sessions/chyunes_mbys.md. Ref: Congress-reel_Masons-apron.wav"
    },
    {
      "id": "the-boys-of-ballisodare",
      "slug": "the-boys-of-ballisodare",
      "name": "The Boys of Ballisodare",
      "tuneType": "Reel",
      "summary": "Imported from Sessions/chyunes_mbys.md."
    },
    {
      "id": "the-crosses-of-annagh",
      "slug": "the-crosses-of-annagh",
      "name": "The Crosses of Annagh",
      "tuneType": "Reel",
      "summary": "Imported from Sessions/chyunes_mbys.md."
    },
    {
      "id": "lord-mcdonalds",
      "slug": "lord-mcdonalds",
      "name": "Lord McDonald's",
      "tuneType": "Reel",
      "summary": "Imported from Sessions/chyunes_mbys.md. Ref: The Boys Of Ballisodare — YouTube"
    },
    {
      "id": "the-silver-spear",
      "slug": "the-silver-spear",
      "name": "The Silver Spear",
      "tuneType": "Reel",
      "summary": "Imported from Sessions/chyunes_mbys.md."
    },
    {
      "id": "the-earls-chair",
      "slug": "the-earls-chair",
      "name": "The Earl's Chair",
      "tuneType": "Reel",
      "summary": "Imported from Sessions/chyunes_mbys.md."
    },
    {
      "id": "the-musical-priest",
      "slug": "the-musical-priest",
      "name": "The Musical Priest",
      "tuneType": "Reel",
      "summary": "Imported from Sessions/chyunes_mbys.md. Ref: The Silver Spear/The Earl's Chair/The Musical Priest (Reels) — YouTube"
    },
    {
      "id": "warlocks",
      "slug": "warlocks",
      "name": "Warlock's",
      "tuneType": "Reel",
      "summary": "Imported from Sessions/chyunes_mbys.md."
    },
    {
      "id": "bog-an-lochan",
      "slug": "bog-an-lochan",
      "name": "Bog an Lochan",
      "tuneType": "Strathspey",
      "summary": "Imported from Sessions/chyunes_mbys.md."
    },
    {
      "id": "keep-it-up",
      "slug": "keep-it-up",
      "name": "Keep it Up",
      "tuneType": "Reel",
      "summary": "Imported from Sessions/chyunes_mbys.md."
    },
    {
      "id": "prince-charlies",
      "slug": "prince-charlies",
      "name": "Prince Charlie's",
      "tuneType": "Reel",
      "summary": "Imported from Sessions/chyunes_mbys.md."
    },
    {
      "id": "hulls-reel",
      "slug": "hulls-reel",
      "name": "Hull's Reel",
      "tuneType": "Reel",
      "summary": "Imported from Sessions/chyunes_mbys.md. Ref: Cape Breton Medley — YouTube"
    },
    {
      "id": "the-rights-of-man",
      "slug": "the-rights-of-man",
      "name": "The Rights of Man",
      "tuneType": "Hornpipe",
      "summary": "Imported from Sessions/chyunes_mbys.md."
    },
    {
      "id": "merrily-kiss-the-quaker",
      "slug": "merrily-kiss-the-quaker",
      "name": "Merrily Kiss the Quaker",
      "tuneType": "Hornpipe",
      "summary": "Imported from Sessions/chyunes_mbys.md."
    },
    {
      "id": "the-kesh-jig",
      "slug": "the-kesh-jig",
      "name": "The Kesh Jig",
      "tuneType": "Jig",
      "summary": "Imported from Sessions/chyunes_mbys.md. Ref: Rites-of-man_Merrily-kiss-the-quaker_Kesh-jig.wav"
    },
    {
      "id": "off-to-california",
      "slug": "off-to-california",
      "name": "Off to California",
      "tuneType": "Hornpipe",
      "summary": "Imported from Sessions/chyunes_mbys.md."
    },
    {
      "id": "temperance-reel",
      "slug": "temperance-reel",
      "name": "Temperance Reel",
      "tuneType": "Reel",
      "summary": "Imported from Sessions/chyunes_mbys.md."
    },
    {
      "id": "wissahickon-drive",
      "slug": "wissahickon-drive",
      "name": "Wissahickon Drive",
      "tuneType": "Hornpipe",
      "summary": "Imported from Sessions/chyunes_mbys.md. Ref: https://www.youtube.com/watch?v=cn25B7Hwx5s"
    },
    {
      "id": "fishers-hornpipe",
      "slug": "fishers-hornpipe",
      "name": "Fisher's Hornpipe",
      "tuneType": "Hornpipe",
      "summary": "Imported from Sessions/chyunes_mbys.md."
    },
    {
      "id": "the-fairies-hornpipe",
      "slug": "the-fairies-hornpipe",
      "name": "The Fairies' Hornpipe",
      "tuneType": "Hornpipe",
      "summary": "Imported from Sessions/chyunes_mbys.md. Ref: Fishers-hornpipe_Faries-hornpipe.wav"
    },
    {
      "id": "tabhair-dom-do-lamh",
      "slug": "tabhair-dom-do-lamh",
      "name": "Tabhair Dom Do Lámh",
      "tuneType": "Waltz",
      "summary": "Imported from Sessions/chyunes_mbys.md. Ref: Tabhair dom do Lámh — YouTube"
    }
  ],
  "tuneAliases": [
    {
      "id": "the-green-mountain-green-mountain",
      "tuneId": "the-green-mountain",
      "name": "Green Mountain",
      "normalizedName": "green mountain"
    },
    {
      "id": "swinging-on-the-gate-swinging-on-a-gate",
      "tuneId": "swinging-on-the-gate",
      "name": "Swinging on a Gate",
      "normalizedName": "swinging on a gate"
    }
  ],
  "charts": [
    {
      "id": "morrisons-jig-chart",
      "slug": "morrisons-jig-chart",
      "tuneId": "morrisons-jig",
      "title": "Morrison's Jig",
      "key": "E",
      "mode": "Minor",
      "meter": "6/8",
      "contentMarkdown": "| Em / / / | / / D / | Em / / / | C / D / |\n\n| Em / / / | / / D / | Em / / / | C / D / |\n| Em / / / | / / D / | C  / / / | D / / / |",
      "visibility": "public"
    },
    {
      "id": "the-butterfly-chart",
      "slug": "the-butterfly-chart",
      "tuneId": "the-butterfly",
      "title": "The Butterfly",
      "key": "E",
      "mode": "Minor",
      "meter": "6/8",
      "contentMarkdown": "|  Em  /  /  |  /  /  D  |  Em  /  /  |  D  /  /  |\n\n|  Am  /  /  |  /  /  Bm  |  Am  /  /  |  /  /  Bm |\n\n|  Em  /  /  |  / / / | D  /  /  |  / / / |\n|  C   /  /  |  / / / | Bm /  /  |  / / / |",
      "visibility": "public"
    },
    {
      "id": "swallowtail-jig-chart",
      "slug": "swallowtail-jig-chart",
      "tuneId": "swallowtail-jig",
      "title": "Swallowtail Jig",
      "key": "E",
      "mode": "Minor",
      "meter": "6/8",
      "contentMarkdown": "| Em /  /  /  |  D  /  /  /  |  Em  /  /  / |  D  /  /  Em |\n\n| Em /  /  /  |  /  /  /  D  |  Em  /  /  / |  /  D  /  Em  |",
      "visibility": "public"
    },
    {
      "id": "saddle-the-pony-chart",
      "slug": "saddle-the-pony-chart",
      "tuneId": "saddle-the-pony",
      "title": "Saddle the Pony",
      "key": "G",
      "mode": "Major",
      "meter": "6/8",
      "contentMarkdown": "| G  / Am / | G / D / | G / Am / | C / D G |\n\n| Em / / / | /  / D / | Em / / / | C / D G |",
      "visibility": "public"
    },
    {
      "id": "lilting-banshee-chart",
      "slug": "lilting-banshee-chart",
      "tuneId": "lilting-banshee",
      "title": "Lilting Banshee",
      "key": "A",
      "mode": "Dorian",
      "meter": "6/8",
      "contentMarkdown": "| Am  /  D  G  |  Em  /  /  G  |  Am  /  D  G  |  Em  /  G  Am  | {A2 alt D}\n\n|  Am  /  /  D  |  G  /  Em  /  |  Am  /  /  D  |  G  /  Em  Am  |\n\n{alt B}|  Am  /  | Bm  /  |  C  /  | D  /  |\n|  Em  /  |  D  /  |  C  / |  D  /  |",
      "visibility": "public"
    },
    {
      "id": "tom-billys-chart",
      "slug": "tom-billys-chart",
      "tuneId": "tom-billys",
      "title": "Tom Billy's",
      "key": "A",
      "mode": "Major",
      "meter": "6/8",
      "contentMarkdown": "|  A  /  /  / |  /  /  /  / |  /  /  /  /  |  G  /  /  (A)  | {A,C}\n\n|  G  /  /  / |  /  /  /  A |  G  /  /  /  |  A  G  A  /  |",
      "visibility": "public"
    },
    {
      "id": "willie-colemans-chart",
      "slug": "willie-colemans-chart",
      "tuneId": "willie-colemans",
      "title": "Willie Coleman's",
      "key": "G",
      "mode": "Major",
      "meter": "6/8",
      "contentMarkdown": "G - C D | or | G - Am D | or build G A B C D\nG - - - | Am - - - | G/B - - - | C - D - |\nEm - - - | Am - - - | G/B - - - | C - D - | {varation}",
      "visibility": "public"
    },
    {
      "id": "connaughtmans-rambles-chart",
      "slug": "connaughtmans-rambles-chart",
      "tuneId": "connaughtmans-rambles",
      "title": "Connaughtman's Rambles",
      "key": "D",
      "mode": "Major",
      "meter": "6/8",
      "contentMarkdown": "|  D  /  G   D  |  D  /  Bm  /  |  D  /  G  /  |  Em  /  Bm  /  |\n\n|  D  G  A   /  |  D  G  A   /  |  D  G  A  /  |  Em  /  Bm   /  |",
      "visibility": "public"
    },
    {
      "id": "the-green-mountain-chart",
      "slug": "the-green-mountain-chart",
      "tuneId": "the-green-mountain",
      "title": "The Green Mountain",
      "key": "D",
      "mode": "Major",
      "meter": "4/4",
      "contentMarkdown": "| D / / / / | Em / G A | D / / / | Em / A D |\n\n| D / G / | Em / A  / | D / G / | Em  / A D |",
      "visibility": "public"
    },
    {
      "id": "wind-that-shakes-the-barley-chart",
      "slug": "wind-that-shakes-the-barley-chart",
      "tuneId": "wind-that-shakes-the-barley",
      "title": "Wind that Shakes the Barley",
      "key": "D",
      "mode": "Major",
      "meter": "4/4",
      "contentMarkdown": "{2x}| D / / / | G / / /  | Bm / / / | A / / / |\n\n{1x}| D G D / | D G A / | D G D / | G / A / |",
      "visibility": "public"
    },
    {
      "id": "swinging-on-the-gate-chart",
      "slug": "swinging-on-the-gate-chart",
      "tuneId": "swinging-on-the-gate",
      "title": "Swinging on the Gate",
      "key": "G",
      "mode": "Major",
      "meter": "4/4",
      "contentMarkdown": "| G / Am / | G / D / | G / Am / | C / D G |\n\n| G / Em / | Am / D / | G / Em / | C / D G |",
      "visibility": "public"
    },
    {
      "id": "man-of-the-house-chart",
      "slug": "man-of-the-house-chart",
      "tuneId": "man-of-the-house",
      "title": "Man of the House",
      "key": "E",
      "mode": "Minor",
      "meter": "4/4",
      "contentMarkdown": "| Em / / D | Em / / / | Em / / D | Em / / / |\n\n| Em D G / | Em / / / | Em D G / | Am  / C  D |",
      "visibility": "public"
    },
    {
      "id": "jackie-colemans-chart",
      "slug": "jackie-colemans-chart",
      "tuneId": "jackie-colemans",
      "title": "Jackie Coleman's",
      "key": "D",
      "mode": "Major",
      "meter": "4/4",
      "contentMarkdown": "| D / / / | Em / A / |\n\n| D / / / | A / / / | Bm / / / | G / A / |",
      "visibility": "public"
    },
    {
      "id": "congress-reel-chart",
      "slug": "congress-reel-chart",
      "tuneId": "congress-reel",
      "title": "Congress Reel",
      "key": "A",
      "mode": "Dorian",
      "meter": "4/4",
      "contentMarkdown": "| Am / / / | / / G / | Am / / / | C / G A |\n\n| Am / / / | G / / / | Am / / / | C / G A |",
      "visibility": "public"
    },
    {
      "id": "masons-apron-chart",
      "slug": "masons-apron-chart",
      "tuneId": "masons-apron",
      "title": "Mason's Apron",
      "key": "A",
      "mode": "Major",
      "meter": "4/4",
      "contentMarkdown": "|  A  /  /  /  |  D   /  /  /  |  A  /  /  / |  D  /  E  A  |\n\n|  A  /  /  /  |  Bm  /  /  /  |  A  /  /  / |  D  /  E  A  |",
      "visibility": "public"
    },
    {
      "id": "the-boys-of-ballisodare-chart",
      "slug": "the-boys-of-ballisodare-chart",
      "tuneId": "the-boys-of-ballisodare",
      "title": "The Boys of Ballisodare",
      "key": "G",
      "mode": "Major",
      "meter": "4/4",
      "contentMarkdown": "| G / / / | G / D / | G / / / | C / / / |\n| G / / / | G / D / | G / D / | C / / / |\n\n| G / / / | G / Em / | G / D / | C / Em / |\n| G / / / | G / Em / | G / Em / | C / Em / |",
      "visibility": "public"
    },
    {
      "id": "the-crosses-of-annagh-chart",
      "slug": "the-crosses-of-annagh-chart",
      "tuneId": "the-crosses-of-annagh",
      "title": "The Crosses of Annagh",
      "key": "E",
      "mode": "Minor",
      "meter": "4/4",
      "contentMarkdown": "| Em / / / | D / / / | Em / / / | D / / / |\n| Em / / / | D / / / | G / A / | Em / / / |\n\n| Em / / / | D / / / | A / / / | G / / / |\n| Em / / / | D / / / | G / A / | Em / / / |",
      "visibility": "public"
    },
    {
      "id": "lord-mcdonalds-chart",
      "slug": "lord-mcdonalds-chart",
      "tuneId": "lord-mcdonalds",
      "title": "Lord McDonald's",
      "key": "G",
      "mode": "Major",
      "meter": "4/4",
      "contentMarkdown": "| G / / / | C / Em / | G / / / | D / G / |\n| G / / / | C / Em / | G / Em / | D / G / |\n\n| G / / / | D / / / | G / / / | Am / G / |\n| G / / / | D / / / | G / / / | C / G / |\n\n| G / / / | G / Em / | G / / / | D / G / |\n| G / / / | G / Em / | G / D / | D / G / |\n\n| G / / / | D / / / | G / / / | Am / G / |\n| G / / / | D / / / | G / / / | C / G / |",
      "visibility": "public"
    },
    {
      "id": "the-silver-spear-chart",
      "slug": "the-silver-spear-chart",
      "tuneId": "the-silver-spear",
      "title": "The Silver Spear",
      "key": "D",
      "mode": "Major",
      "meter": "4/4",
      "contentMarkdown": "{first A+B}| D5 / | ... | D (C#) G Am | G (F#) Em A |\n\n| D / / / | G / A / | D / / / | G / A / |\n\n| D / / / | Bm / G A | D / Em D | G D Em A |",
      "visibility": "public"
    },
    {
      "id": "the-earls-chair-chart",
      "slug": "the-earls-chair-chart",
      "tuneId": "the-earls-chair",
      "title": "The Earl's Chair",
      "key": "D",
      "mode": "Major",
      "meter": "4/4",
      "contentMarkdown": "| Bm /  G / / | D / / / | Bm / G / | D / A D |\n\n| A D A D | A / D / | Em / G / | D G A D |",
      "visibility": "public"
    },
    {
      "id": "the-musical-priest-chart",
      "slug": "the-musical-priest-chart",
      "tuneId": "the-musical-priest",
      "title": "The Musical Priest",
      "key": "G",
      "mode": "Dorian",
      "meter": "4/4",
      "contentMarkdown": "| Gm / / / | / / F / | Gm / / / | F / / / |\n\n| Bb / F / | Bb / F Gm |\n\n| Gm / C / |",
      "visibility": "public"
    },
    {
      "id": "warlocks-chart",
      "slug": "warlocks-chart",
      "tuneId": "warlocks",
      "title": "Warlock's",
      "key": "E",
      "mode": "Dorian",
      "meter": "4/4",
      "contentMarkdown": "|  Em  /  /  / |  D  /  /  / |  Em(G)  /  /  / |  D  /  Em  / |\n\n|  Em  /  /  / |  D  /  /  / |  C  /  /  / |  D  /  Em  / |",
      "visibility": "public"
    },
    {
      "id": "bog-an-lochan-chart",
      "slug": "bog-an-lochan-chart",
      "tuneId": "bog-an-lochan",
      "title": "Bog an Lochan",
      "key": "E",
      "mode": "Dorian",
      "meter": "4/4",
      "contentMarkdown": "|  Em  /  /  / |  /  /  D  / |  Em  /  /  / |  G  /  D  / |\n\n|  Em  /  /  / |  /  /  D  / |  Em  /  /  / |  /  /  D  / |",
      "visibility": "public"
    },
    {
      "id": "keep-it-up-chart",
      "slug": "keep-it-up-chart",
      "tuneId": "keep-it-up",
      "title": "Keep it Up",
      "key": "E",
      "mode": "Mixolydian",
      "meter": "4/4",
      "contentMarkdown": "|  Em  /  /  / |  D  /  /  / |  Em  /  /  / |  G  /  D  / |\n\n|  Em  /  /  / |  D  /  /  / |  C  /  /  / |  D  /  Em  / |",
      "visibility": "public"
    },
    {
      "id": "prince-charlies-chart",
      "slug": "prince-charlies-chart",
      "tuneId": "prince-charlies",
      "title": "Prince Charlie's",
      "key": "E",
      "mode": "Dorian",
      "meter": "4/4",
      "contentMarkdown": "|  Em  /  G  / |  D  /  /  / |  Em  /  G  / |  D  /  /  / |\n|  Em  /  G  / |  D  /  /  / |  C  /  /  / |  D  /  Em  / |\n\n|  Em  /  /  / |  D  /  /  / |  C  /  /  / |  D  /  Em  / |",
      "visibility": "public"
    },
    {
      "id": "hulls-reel-chart",
      "slug": "hulls-reel-chart",
      "tuneId": "hulls-reel",
      "title": "Hull's Reel",
      "key": "E",
      "mode": "Major",
      "meter": "4/4",
      "contentMarkdown": "|  E  /  /  / |  /  /  A  / |  E  /  A  / |  E  /  B  / |\n|  E  /  /  / |  /  /  A  / |  E  /  A  / |  B  /  E  / |\n\n|  E  /  /  / |  A  /  /  / |  F#m  /  /  / |  B  /  /  / |",
      "visibility": "public"
    },
    {
      "id": "the-rights-of-man-chart",
      "slug": "the-rights-of-man-chart",
      "tuneId": "the-rights-of-man",
      "title": "The Rights of Man",
      "key": "E",
      "mode": "Minor",
      "meter": "4/4",
      "contentMarkdown": "| Em / / / | / / D Bm |\n| Em / / / | / Bm Em / |\n\n| Em / / / | D / / Bm |\n| Em D Em / | / Bm Em / |",
      "visibility": "public"
    },
    {
      "id": "merrily-kiss-the-quaker-chart",
      "slug": "merrily-kiss-the-quaker-chart",
      "tuneId": "merrily-kiss-the-quaker",
      "title": "Merrily Kiss the Quaker",
      "key": "G",
      "mode": "Major",
      "meter": "4/4",
      "contentMarkdown": "|  G  /  Am  /  |  G  /  D  / |  G  / Am /  | C  D  G  /  |\n\n|  G  /  /  /  |  /  /  D  / |  G  /  / /  |  /  D  G  /  |\n\n|  Em  /  /  /  |  /  /  D  / |  C  G  Am /  |  C  D  G  /  |",
      "visibility": "public"
    },
    {
      "id": "the-kesh-jig-chart",
      "slug": "the-kesh-jig-chart",
      "tuneId": "the-kesh-jig",
      "title": "The Kesh Jig",
      "key": "G",
      "mode": "Major",
      "meter": "6/8",
      "contentMarkdown": "|  G  /  D  / |  C  /  / D  |  G  /  D /  |  C  /  D G  |\n\n|  G  /  C  G |  G  /  Am /  |  G  /  C G  |  C  D  /  G |",
      "visibility": "public"
    },
    {
      "id": "off-to-california-chart",
      "slug": "off-to-california-chart",
      "tuneId": "off-to-california",
      "title": "Off to California",
      "key": "G",
      "mode": "Major",
      "meter": "4/4",
      "contentMarkdown": "| G / Am / | C/B / C / | G / Em / | Am / D / |\n\n| Em / D / | C / Bm / | Em / D / | Amaj / D / |",
      "visibility": "public"
    },
    {
      "id": "temperance-reel-chart",
      "slug": "temperance-reel-chart",
      "tuneId": "temperance-reel",
      "title": "Temperance Reel",
      "key": "G",
      "mode": "Major",
      "meter": "4/4",
      "contentMarkdown": "|  G  /  /  /  |  Em  /  D  /   |  G  /  /  /  |  C  /  D  G  |\n\n|  Em  /  /  /  |  D  /  /  /  |  Em  /  /  /  |  D  /  /  G  |",
      "visibility": "public"
    },
    {
      "id": "wissahickon-drive-chart",
      "slug": "wissahickon-drive-chart",
      "tuneId": "wissahickon-drive",
      "title": "Wissahickon Drive",
      "key": "A",
      "mode": "Major",
      "meter": "4/4",
      "contentMarkdown": "|  A  /  /  /  |  Bm  /  /  E  |  A  /  /  /  |  D  /  E  A  |\n\n|  A  /  D  /  |  A  /  E  /  |  A  /  D  /  |  A  /  E  A    |",
      "visibility": "public"
    },
    {
      "id": "fishers-hornpipe-chart",
      "slug": "fishers-hornpipe-chart",
      "tuneId": "fishers-hornpipe",
      "title": "Fisher's Hornpipe",
      "key": "D",
      "mode": "Major",
      "meter": "4/4",
      "contentMarkdown": "| D / G A | D / G A | D / Em / | D / A / |\n| D / G A | D / G A | D / Em / | A / D / |\n\n| A / / / | D / / / | A / / / | / / / . |\n| G / / / | D / / / | A / / / | D / / / |",
      "visibility": "public"
    },
    {
      "id": "the-fairies-hornpipe-chart",
      "slug": "the-fairies-hornpipe-chart",
      "tuneId": "the-fairies-hornpipe",
      "title": "The Fairies' Hornpipe",
      "key": "G",
      "mode": "Major",
      "meter": "4/4",
      "contentMarkdown": "| G . . B/C | D F# G B | G F# E D | A B/C D / |\n| G / / / | / / / / | A/B C D C | B A G . |\n\n| G / / / | / / / / | A / /B C | F# E D . |\n| G / / / | / / / / | A/B C D C | B A G . |",
      "visibility": "public"
    },
    {
      "id": "tabhair-dom-do-lamh-chart",
      "slug": "tabhair-dom-do-lamh-chart",
      "tuneId": "tabhair-dom-do-lamh",
      "title": "Tabhair Dom Do Lámh",
      "key": "G",
      "mode": "Major",
      "meter": "3/4",
      "contentMarkdown": "|  C  G |  C  G  |\n| C  G   |  Em  Bm |\n|  D  Bm  |  Am  Em  |\n\n| C  G |  C  G  |\n|  C  Em  |  Dadd6  G  |\n\n|  C  G  |  Em  G  |\n| D  Bm  |  Am  C  |\n|  D  G  |  Em  Am7  |\n\n|  G  Em  |  G  Em  |\n| G  Em  |  Am  D  |\n\n|  C  G  |  Bm  Am  |\n|  G  F  |  C  C-G-Am |\n|  G  Em |  Dadd6 G |\n\n{end}| C G | C G |\n| C Em | D  C |\n| G  |",
      "visibility": "public"
    }
  ],
  "sets": [
    {
      "id": "morrisons-jig-the-butterfly-swallowtail-jig",
      "slug": "morrisons-jig-the-butterfly-swallowtail-jig",
      "name": "Morrison's Jig / The Butterfly / Swallowtail Jig",
      "summary": "Imported from the JIGS section of Sessions/chyunes_mbys.md.",
      "visibility": "public",
      "entries": [
        {
          "position": 1,
          "tuneId": "morrisons-jig",
          "chartId": "morrisons-jig-chart"
        },
        {
          "position": 2,
          "tuneId": "the-butterfly",
          "chartId": "the-butterfly-chart"
        },
        {
          "position": 3,
          "tuneId": "swallowtail-jig",
          "chartId": "swallowtail-jig-chart"
        }
      ]
    },
    {
      "id": "saddle-the-pony-lilting-banshee-tom-billys",
      "slug": "saddle-the-pony-lilting-banshee-tom-billys",
      "name": "Saddle the Pony / Lilting Banshee / Tom Billy's",
      "summary": "Imported from the JIGS section of Sessions/chyunes_mbys.md.",
      "visibility": "public",
      "entries": [
        {
          "position": 1,
          "tuneId": "saddle-the-pony",
          "chartId": "saddle-the-pony-chart"
        },
        {
          "position": 2,
          "tuneId": "lilting-banshee",
          "chartId": "lilting-banshee-chart"
        },
        {
          "position": 3,
          "tuneId": "tom-billys",
          "chartId": "tom-billys-chart"
        }
      ]
    },
    {
      "id": "willie-colemans",
      "slug": "willie-colemans",
      "name": "Willie Coleman's",
      "summary": "Imported from the JIGS section of Sessions/chyunes_mbys.md. Marked [drop] in the source. 2 source titles in this group could not be imported because no recoverable chart content exists.",
      "visibility": "public",
      "entries": [
        {
          "position": 1,
          "tuneId": "willie-colemans",
          "chartId": "willie-colemans-chart"
        }
      ]
    },
    {
      "id": "connaughtmans-rambles",
      "slug": "connaughtmans-rambles",
      "name": "Connaughtman's Rambles",
      "summary": "Imported from the JIGS section of Sessions/chyunes_mbys.md. 1 source title in this group could not be imported because no recoverable chart content exists.",
      "visibility": "public",
      "entries": [
        {
          "position": 1,
          "tuneId": "connaughtmans-rambles",
          "chartId": "connaughtmans-rambles-chart"
        }
      ]
    },
    {
      "id": "the-green-mountain-wind-that-shakes-the-barley",
      "slug": "the-green-mountain-wind-that-shakes-the-barley",
      "name": "The Green Mountain / Wind that Shakes the Barley",
      "summary": "Imported from the REELS section of Sessions/chyunes_mbys.md.",
      "visibility": "public",
      "entries": [
        {
          "position": 1,
          "tuneId": "the-green-mountain",
          "chartId": "the-green-mountain-chart"
        },
        {
          "position": 2,
          "tuneId": "wind-that-shakes-the-barley",
          "chartId": "wind-that-shakes-the-barley-chart"
        }
      ]
    },
    {
      "id": "swinging-on-the-gate-man-of-the-house-jackie-colemans",
      "slug": "swinging-on-the-gate-man-of-the-house-jackie-colemans",
      "name": "Swinging on the Gate / Man of the House / Jackie Coleman's",
      "summary": "Imported from the REELS section of Sessions/chyunes_mbys.md.",
      "visibility": "public",
      "entries": [
        {
          "position": 1,
          "tuneId": "swinging-on-the-gate",
          "chartId": "swinging-on-the-gate-chart"
        },
        {
          "position": 2,
          "tuneId": "man-of-the-house",
          "chartId": "man-of-the-house-chart"
        },
        {
          "position": 3,
          "tuneId": "jackie-colemans",
          "chartId": "jackie-colemans-chart"
        }
      ]
    },
    {
      "id": "congress-reel-masons-apron",
      "slug": "congress-reel-masons-apron",
      "name": "Congress Reel / Mason's Apron",
      "summary": "Imported from the REELS section of Sessions/chyunes_mbys.md.",
      "visibility": "public",
      "entries": [
        {
          "position": 1,
          "tuneId": "congress-reel",
          "chartId": "congress-reel-chart"
        },
        {
          "position": 2,
          "tuneId": "masons-apron",
          "chartId": "masons-apron-chart"
        }
      ]
    },
    {
      "id": "the-boys-of-ballisodare-the-crosses-of-annagh-lord-mcdonalds",
      "slug": "the-boys-of-ballisodare-the-crosses-of-annagh-lord-mcdonalds",
      "name": "The Boys of Ballisodare / The Crosses of Annagh / Lord McDonald's",
      "summary": "Imported from the REELS section of Sessions/chyunes_mbys.md. Marked [drop] in the source.",
      "visibility": "public",
      "entries": [
        {
          "position": 1,
          "tuneId": "the-boys-of-ballisodare",
          "chartId": "the-boys-of-ballisodare-chart"
        },
        {
          "position": 2,
          "tuneId": "the-crosses-of-annagh",
          "chartId": "the-crosses-of-annagh-chart"
        },
        {
          "position": 3,
          "tuneId": "lord-mcdonalds",
          "chartId": "lord-mcdonalds-chart"
        }
      ]
    },
    {
      "id": "the-silver-spear-the-earls-chair-the-musical-priest",
      "slug": "the-silver-spear-the-earls-chair-the-musical-priest",
      "name": "The Silver Spear / The Earl's Chair / The Musical Priest",
      "summary": "Imported from the REELS section of Sessions/chyunes_mbys.md.",
      "visibility": "public",
      "entries": [
        {
          "position": 1,
          "tuneId": "the-silver-spear",
          "chartId": "the-silver-spear-chart"
        },
        {
          "position": 2,
          "tuneId": "the-earls-chair",
          "chartId": "the-earls-chair-chart"
        },
        {
          "position": 3,
          "tuneId": "the-musical-priest",
          "chartId": "the-musical-priest-chart"
        }
      ]
    },
    {
      "id": "warlocks-bog-an-lochan-keep-it-up-prince-charlies-hulls-reel",
      "slug": "warlocks-bog-an-lochan-keep-it-up-prince-charlies-hulls-reel",
      "name": "Warlock's / Bog an Lochan / Keep it Up / Prince Charlie's / Hull's Reel",
      "summary": "Imported from the STRATHSPEYS → REELS section of Sessions/chyunes_mbys.md.",
      "visibility": "public",
      "entries": [
        {
          "position": 1,
          "tuneId": "warlocks",
          "chartId": "warlocks-chart"
        },
        {
          "position": 2,
          "tuneId": "bog-an-lochan",
          "chartId": "bog-an-lochan-chart"
        },
        {
          "position": 3,
          "tuneId": "keep-it-up",
          "chartId": "keep-it-up-chart"
        },
        {
          "position": 4,
          "tuneId": "prince-charlies",
          "chartId": "prince-charlies-chart"
        },
        {
          "position": 5,
          "tuneId": "hulls-reel",
          "chartId": "hulls-reel-chart"
        }
      ]
    },
    {
      "id": "the-rights-of-man-merrily-kiss-the-quaker-the-kesh-jig",
      "slug": "the-rights-of-man-merrily-kiss-the-quaker-the-kesh-jig",
      "name": "The Rights of Man / Merrily Kiss the Quaker / The Kesh Jig",
      "summary": "Imported from the HORNPIPES section of Sessions/chyunes_mbys.md.",
      "visibility": "public",
      "entries": [
        {
          "position": 1,
          "tuneId": "the-rights-of-man",
          "chartId": "the-rights-of-man-chart"
        },
        {
          "position": 2,
          "tuneId": "merrily-kiss-the-quaker",
          "chartId": "merrily-kiss-the-quaker-chart"
        },
        {
          "position": 3,
          "tuneId": "the-kesh-jig",
          "chartId": "the-kesh-jig-chart"
        }
      ]
    },
    {
      "id": "off-to-california-temperance-reel-wissahickon-drive",
      "slug": "off-to-california-temperance-reel-wissahickon-drive",
      "name": "Off to California / Temperance Reel / Wissahickon Drive",
      "summary": "Imported from the HORNPIPES section of Sessions/chyunes_mbys.md.",
      "visibility": "public",
      "entries": [
        {
          "position": 1,
          "tuneId": "off-to-california",
          "chartId": "off-to-california-chart"
        },
        {
          "position": 2,
          "tuneId": "temperance-reel",
          "chartId": "temperance-reel-chart"
        },
        {
          "position": 3,
          "tuneId": "wissahickon-drive",
          "chartId": "wissahickon-drive-chart"
        }
      ]
    },
    {
      "id": "fishers-hornpipe-the-fairies-hornpipe",
      "slug": "fishers-hornpipe-the-fairies-hornpipe",
      "name": "Fisher's Hornpipe / The Fairies' Hornpipe",
      "summary": "Imported from the HORNPIPES section of Sessions/chyunes_mbys.md.",
      "visibility": "public",
      "entries": [
        {
          "position": 1,
          "tuneId": "fishers-hornpipe",
          "chartId": "fishers-hornpipe-chart"
        },
        {
          "position": 2,
          "tuneId": "the-fairies-hornpipe",
          "chartId": "the-fairies-hornpipe-chart"
        }
      ]
    },
    {
      "id": "tabhair-dom-do-lamh",
      "slug": "tabhair-dom-do-lamh",
      "name": "Tabhair Dom Do Lámh",
      "summary": "Imported from the WALTZES section of Sessions/chyunes_mbys.md.",
      "visibility": "public",
      "entries": [
        {
          "position": 1,
          "tuneId": "tabhair-dom-do-lamh",
          "chartId": "tabhair-dom-do-lamh-chart"
        }
      ]
    }
  ],
  "gigSheets": [
    {
      "id": "st-paddys-day",
      "slug": "st-paddys-day",
      "name": "St. Paddy's Day 2026",
      "summary": "Derived from the checked-in St. Paddy's Day PDF by reusing the non-[drop] public source groups from Sessions/chyunes_mbys.md in source order.",
      "visibility": "private",
      "entries": [
        {
          "position": 1,
          "setId": "morrisons-jig-the-butterfly-swallowtail-jig"
        },
        {
          "position": 2,
          "setId": "saddle-the-pony-lilting-banshee-tom-billys"
        },
        {
          "position": 3,
          "setId": "connaughtmans-rambles"
        },
        {
          "position": 4,
          "setId": "the-green-mountain-wind-that-shakes-the-barley"
        },
        {
          "position": 5,
          "setId": "swinging-on-the-gate-man-of-the-house-jackie-colemans"
        },
        {
          "position": 6,
          "setId": "congress-reel-masons-apron"
        },
        {
          "position": 7,
          "setId": "the-silver-spear-the-earls-chair-the-musical-priest"
        },
        {
          "position": 8,
          "setId": "warlocks-bog-an-lochan-keep-it-up-prince-charlies-hulls-reel"
        },
        {
          "position": 9,
          "setId": "the-rights-of-man-merrily-kiss-the-quaker-the-kesh-jig"
        },
        {
          "position": 10,
          "setId": "off-to-california-temperance-reel-wissahickon-drive"
        },
        {
          "position": 11,
          "setId": "fishers-hornpipe-the-fairies-hornpipe"
        },
        {
          "position": 12,
          "setId": "tabhair-dom-do-lamh"
        }
      ]
    }
  ]
};
