import { writeFileSync } from "node:fs";
import path from "node:path";

import { buildRelease1Import } from "../src/lib/release-1/import-source";

function main() {
  const { store, excludedSourceTitles } = buildRelease1Import();
  const outputPath = path.join(process.cwd(), "src/data/release-1/fixture-store.ts");
  const output = `import type { Release1Store } from "@/lib/release-1/schema";\n\n// Generated by npm run generate:release-1-data\n// Excluded source titles: ${excludedSourceTitles.join(", ")}\nexport const release1FixtureStore: Release1Store = ${JSON.stringify(store, null, 2)};\n`;

  writeFileSync(outputPath, output);
  console.log(`Wrote ${outputPath}`);
}

main();
