# This file was adapted from the Firebase CLI defaults.

name: Deploy production on tag
on:
  push:
    tags:
      - "v*"
jobs:
  deploy_production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm run test
      - run: npm run typecheck
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SESSIONBOOK_491003 }}
          projectId: sessionbook-491003
          channelId: live
          target: prod
